services:
  meeting:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: meeting
    ports:
      - "8000:8000"
    command: "uvicorn src.main:app --reload --use-colors --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge
